from __future__ import annotations

from typing import Any, Protocol, TypeVar

from portable_runtime.core.models import (
    Action,
    Artifact,
    Checkpoint,
    Compensation,
    Decision,
    Event,
    Evidence,
    KnowledgeItem,
    Outcome,
    Run,
    Step,
    StepAttempt,
    Work,
)
from portable_runtime.experience.historical_use import (
    HistoricalExperienceUse,
    HistoricalExperienceUseCommitRequest,
)
from portable_runtime.records.knowledge import KnowledgeProjection
from portable_runtime.records.models import BaseRecord, OutcomeRecord
from portable_runtime.records.relations import RecordRelation
from portable_runtime.records.verified_outcome_commit import VerifiedOutcomeCommitRequest

T = TypeVar("T")


class StateStore(Protocol):
    def save_work(self, value: Work) -> None: ...
    def get_work(self, work_id: str) -> Work | None: ...
    def list_work(self, status: str | None = None) -> list[Work]: ...

    def save_run(self, value: Run) -> None: ...
    def get_run(self, run_id: str) -> Run | None: ...
    def list_runs(self, work_id: str | None = None) -> list[Run]: ...

    def save_artifact(self, value: Artifact) -> None: ...
    def get_artifact(self, artifact_id: str) -> Artifact | None: ...

    def save_evidence(self, value: Evidence) -> None: ...
    def get_evidence(self, evidence_id: str) -> Evidence | None: ...
    def list_evidence(self, subject_ref: str | None = None) -> list[Evidence]: ...
    # Raw legacy namespace used only by canonical migration/consolidation.
    # ``list_evidence`` is a compatibility view and may include canonical
    # records projected back into the legacy shape.
    def list_raw_legacy_evidence(self, subject_ref: str | None = None) -> list[Evidence]: ...

    def save_decision(self, value: Decision) -> None: ...
    def get_decision(self, decision_id: str) -> Decision | None: ...
    def save_action(self, value: Action) -> None: ...
    def get_action(self, action_id: str) -> Action | None: ...
    def save_outcome(self, value: Outcome) -> None: ...
    def save_knowledge(self, value: KnowledgeItem) -> None: ...
    def get_knowledge(self, knowledge_id: str) -> KnowledgeItem | None: ...
    def list_knowledge(self, status: str | None = None) -> list[KnowledgeItem]: ...
    # Raw legacy namespace used only by canonical migration/consolidation.
    # ``list_knowledge`` remains a read-compatibility view and must not be
    # used as canonical ingestion input.
    def list_raw_legacy_knowledge(self, status: str | None = None) -> list[KnowledgeItem]: ...
    # Canonical knowledge path.
    def save_knowledge_projection(self, value: KnowledgeProjection) -> None: ...
    def get_knowledge_projection(self, projection_id: str) -> KnowledgeProjection | None: ...
    def list_knowledge_projections(self, status: str | None = None) -> list[KnowledgeProjection]: ...

    def append_event(self, value: Event) -> None: ...
    def get_event(self, event_id: str) -> Event | None: ...
    def list_events(self, subject_ref: str | None = None) -> list[Event]: ...
    def export_state(self) -> dict[str, list[dict[str, object]]]: ...
    def import_state(self, state: dict[str, list[dict[str, object]]]) -> None: ...

    # R1.1 Execution Integrity extensions (optional for conformance, default fallback)
    def save_step(self, value: Step) -> None: ...
    def get_step(self, step_id: str) -> Step | None: ...
    def list_steps(self, run_id: str | None = None) -> list[Step]: ...
    def list_stale_steps(self, before_seconds: float = 30) -> list[Step]: ...
    def save_attempt(self, value: StepAttempt) -> None: ...
    def get_attempt(self, attempt_id: str) -> StepAttempt | None: ...
    def list_attempts(self, step_id: str | None = None) -> list[StepAttempt]: ...
    def save_checkpoint(self, value: Checkpoint) -> None: ...
    def get_checkpoint(self, checkpoint_id: str) -> Checkpoint | None: ...
    def save_compensation(self, value: Compensation) -> None: ...
    def compare_and_swap(self, kind: str, identifier: str, expected_version: int, new_value: Any) -> bool: ...
    def transaction(self) -> Any: ...
    # Atomic authority primitives. Stores own validation and durable commit;
    # callers cannot append the corresponding authority events directly.
    def commit_terminal(self, work: Work, run: Run, verification_refs: list[str]) -> Run: ...
    def commit_verified_outcome(self, request: VerifiedOutcomeCommitRequest) -> OutcomeRecord: ...
    def commit_historical_experience_use(
        self, request: HistoricalExperienceUseCommitRequest
    ) -> HistoricalExperienceUse: ...
    def commit_recovery_observation(self, request: Any) -> Any: ...
    def commit_recovery_disposition(self, request: Any, policy: Any) -> Any: ...
    def commit_recovery_application(self, request: Any) -> Any: ...
    def acquire_lease(self, run_id: str, owner: str, ttl_seconds: float = 30) -> bool: ...
    def renew_lease(self, run_id: str, owner: str, ttl_seconds: float = 30) -> bool: ...
    def release_lease(self, run_id: str, owner: str) -> bool: ...

    # R1.2 Semantic Records
    def save_record(self, value: BaseRecord) -> None: ...
    def get_record(self, record_id: str) -> BaseRecord | None: ...
    def list_records(self, record_type: str | None = None) -> list[BaseRecord]: ...
    def save_relation(self, value: RecordRelation) -> None: ...
    def get_relation(self, relation_id: str) -> RecordRelation | None: ...
    def list_relations(self, relation_type: str | None = None) -> list[RecordRelation]: ...
    def save_authorization_use(self, value: Any) -> None: ...
    def get_authorization_use(self, use_id: str) -> Any | None: ...
    def list_authorization_uses(self) -> list[Any]: ...
