from __future__ import annotations

from typing import Protocol, TypeVar

from portable_runtime.core.models import (
    Action,
    Artifact,
    Decision,
    Event,
    Evidence,
    KnowledgeItem,
    Outcome,
    Run,
    Work,
)

T = TypeVar("T")


class StateStore(Protocol):
    def save_work(self, value: Work) -> None: ...
    def get_work(self, work_id: str) -> Work | None: ...
    def list_work(self, status: str | None = None) -> list[Work]: ...

    def save_run(self, value: Run) -> None: ...
    def get_run(self, run_id: str) -> Run | None: ...
    def list_runs(self, work_id: str | None = None) -> list[Run]: ...

    def save_artifact(self, value: Artifact) -> None: ...
    def get_artifact(self, artifact_id: str) -> Artifact | None: ...

    def save_evidence(self, value: Evidence) -> None: ...
    def list_evidence(self, subject_ref: str | None = None) -> list[Evidence]: ...

    def save_decision(self, value: Decision) -> None: ...
    def save_action(self, value: Action) -> None: ...
    def save_outcome(self, value: Outcome) -> None: ...
    def save_knowledge(self, value: KnowledgeItem) -> None: ...
    def get_knowledge(self, knowledge_id: str) -> KnowledgeItem | None: ...
    def list_knowledge(self, status: str | None = None) -> list[KnowledgeItem]: ...

    def append_event(self, value: Event) -> None: ...
    def export_state(self) -> dict[str, list[dict[str, object]]]: ...
    def import_state(self, state: dict[str, list[dict[str, object]]]) -> None: ...
